name: ci

on:
  push:
  pull_request:

jobs:
  python-ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12", "3.13"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]
          pip install pre-commit
      - name: Run pre-commit (black, ruff, mypy)
        run: pre-commit run --all-files
      - name: Run tests
        run: pytest -q
